task

diff --git a/0x00-python-hello_world/0-run b/0x00-python-hello_world/0-run
--- a/0x00-python-hello_world/0-run
+++ b/0x00-python-hello_world/0-run
@@ -1,16 +1,4 @@
 #!/bin/bash
-
-# Check if $PYFILE is set
-if [ -z "$PYFILE" ]; then
-    echo "Error: Environment variable \$PYFILE is not set."
-    exit 1
-fi
-
-# Check if the specified Python file exists
-if [ ! -f "$PYFILE" ]; then
-    echo "Error: Python file '$PYFILE' not found."
-    exit 1
-fi
-
-# Run the Python script
+[ -z "$PYFILE" ] && { echo "Error: PYFILE environment variable is not set."; exit 1; }
+[ -f "$PYFILE" ] || { echo "Error: Python file '$PYFILE' not found."; exit 1; }
 python3 "$PYFILE"
